version: "3"

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  tests:
    build: .
    command: pytest /tests
    volumes:
      - ./tests:/tests
      - ./models:/app/models
    depends_on:
      - app